# Generated by Django 5.1.6 on 2025-02-08 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaperChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('diaper_type', models.CharField(choices=[('wet', 'Wet'), ('dirty', 'Dirty'), ('mixed', 'Mixed')], max_length=10)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaper_changes', to='tracker.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('feeding_type', models.CharField(choices=[('breastfeeding', 'Breastfeeding'), ('bottle', 'Bottle'), ('solid', 'Solid Food')], max_length=20)),
                ('quantity', models.FloatField(help_text='Amount in ounces/ml')),
                ('last_side', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], max_length=10, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='tracker.baby')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_milestones', to='tracker.baby')),
            ],
        ),
        migrations.CreateModel(
            name='PumpingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], max_length=10)),
                ('quantity', models.FloatField(help_text='Milk pumped in ounces/ml')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumping_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tracker.baby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_sessions', to='tracker.baby')),
            ],
        ),
    ]
