# Generated by Django 5.1.6 on 2025-02-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpingsession',
            name='side',
            field=models.CharField(choices=[('left_pump', 'Left'), ('right_pump', 'Right'), ('both_pump', 'Both')], max_length=10),
        ),
    ]
