# Generated by Django 5.1.6 on 2025-02-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_pumpingsession_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpingsession',
            name='side',
            field=models.CharField(choices=[('left_pump', 'Left'), ('right_pump', 'Right'), ('both_pump', 'Both')], max_length=12),
        ),
    ]
