# Generated by Django 5.1.6 on 2025-02-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_pumpingsession_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='last_side',
            field=models.CharField(blank=True, choices=[('left_feeding', 'Left'), ('right_feeding', 'Right'), ('both_feeding', 'Both')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pumpingsession',
            name='side',
            field=models.CharField(choices=[('left_pump', 'Left'), ('right_pump', 'Right'), ('both_pump', 'Both')], max_length=15),
        ),
    ]
