# Generated by Django 5.1.6 on 2025-02-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_feeding_last_side_alter_pumpingsession_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='last_side',
            field=models.CharField(blank=True, choices=[('left_feeding', 'LEFT'), ('right_feeding', 'RIGHT'), ('both_feeding', 'BOTH')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pumpingsession',
            name='side',
            field=models.CharField(choices=[('left_pump', 'LEFT'), ('right_pump', 'RIGHT'), ('both_pump', 'BOTH')], max_length=15),
        ),
    ]
