# Generated by Django 5.1.6 on 2025-04-04 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_feeding_last_side_alter_pumpingsession_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('social', 'Social'), ('cognitive', 'Cognitive'), ('language', 'Language'), ('emotional', 'Emotional')], max_length=20)),
                ('date_achieved', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tracker.baby')),
            ],
        ),
    ]
