# Generated by Django 4.2.10 on 2026-01-23 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0009_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField()),
                ('category', models.CharField(default='baby food', max_length=100)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='baby',
            name='birth_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='diaperchange',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='end_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='baby',
            index=models.Index(fields=['user', 'name'], name='tracker_bab_user_id_682dec_idx'),
        ),
        migrations.AddIndex(
            model_name='baby',
            index=models.Index(fields=['user', 'birth_date'], name='tracker_bab_user_id_7ff804_idx'),
        ),
        migrations.AddIndex(
            model_name='diaperchange',
            index=models.Index(fields=['baby', 'time'], name='tracker_dia_baby_id_b79d61_idx'),
        ),
        migrations.AddIndex(
            model_name='diaperchange',
            index=models.Index(fields=['baby', 'diaper_type'], name='tracker_dia_baby_id_f3e030_idx'),
        ),
        migrations.AddIndex(
            model_name='feeding',
            index=models.Index(fields=['baby', 'time'], name='tracker_fee_baby_id_49cf3e_idx'),
        ),
        migrations.AddIndex(
            model_name='feeding',
            index=models.Index(fields=['baby', 'feeding_type'], name='tracker_fee_baby_id_8657f3_idx'),
        ),
        migrations.AddIndex(
            model_name='sleep',
            index=models.Index(fields=['baby', 'start_time'], name='tracker_sle_baby_id_a8dd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='sleep',
            index=models.Index(fields=['baby', 'end_time'], name='tracker_sle_baby_id_dc9509_idx'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='tracker.recipe'),
        ),
    ]
