# Generated by Django 4.2.10 on 2026-01-24 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_ingredient_recipe_alter_baby_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('social', 'Social'), ('cognitive', 'Cognitive'), ('language', 'Language'), ('emotional', 'Emotional')], max_length=20)),
                ('date_achieved', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developmental_milestones', to='tracker.baby')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('notes', models.TextField(blank=True, null=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_measurements', to='tracker.baby')),
            ],
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='baby',
        ),
        migrations.DeleteModel(
            name='GrowthMilestone',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
